### ISSUE TITLE
Building safe_launcher and 'npm start'

### ISSUE THREAD

**Issue by theWebalyst** [maidsafe/safe_launcher#115]
According to safe_launcher/README.md I have built safe_ffi, copied libsafe_ffi.so to safe_launcher/app/api/ffi/

In safe_launcher:
```
npm install
```
seems fine.
```
npm start
```
Runs the launcher which accepts credentials and on clicking Login, displays a message I've not seen in the downloaded launcher: ```Waiting for establishing connection with SAFE Network```

I'm guessing there's a problem with safe_ffi. Any clues as to why I might not be getting a successful build here?

I'm on Debian and ```git status``` shows:
```
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	app/api/ffi/libsafe_ffi.so
	src/
	target/
```

**Comment by theWebalyst** [comment]
I'm wondering if the issue is that I'm building the launcher without some magic sauce that is needed to allow it to connect to the testnet. Will as on slack...

**Comment by theWebalyst** [comment]
Ok first magic sauce required is to be on branch "dev". That helps and I now get to "Loggin in..." but it always fails so I'm not sure if this version can get on the testnet.

**Comment by theWebalyst** [comment]
Further info: on the demo launcer I see the network connection status in a blue banner at the top of the launcher window. With my local "npm start" launcher I don't see a banner, which explains why the login fails. So.. why doesn't it connect?

**Comment by krishnaIndia** [comment]
`npm  start` would need the ffi to built using the mock feature 
`cargo build --release --features use-mock-routing`.

If you want to test it against the vaults, then you will have to set up a local network and then build ffi without the mock feature `cargo build --release`

But if you are specific to connect to the existing test network, then you will have to use `npm run package` command,  this will package the application with the production flag and place it in the `app_dist` folder. You will need to provide the `crust config` file for the application to bootstrap to the network. You can find this `crust config file (safe_launcher.crust.config)` from the release binaries. This file has to be placed in the same folder where you have the packaged `safe_launcher` binary. 

Since this application is packaged in the production mode, the console debuggers will not be available. If you want to debug after packaging the application you can change the configuration [here to use the development flag](https://github.com/maidsafe/safe_launcher/blob/master/package.json#L36) or simple run `gulp package`, if gulp is installed globally.

I will also update the readme specifying the requirement of building ffi against mock or using a local network for development.

**Comment by theWebalyst** [comment]
Thanks Krishna, excellent!
