### ISSUE TITLE
README.MD instructions for building safe_core don't produce libsafe_core.so

### ISSUE THREAD

**Issue by theWebalyst** [maidsafe/safe_launcher#246]
README.MD states:
```
The development dependency of this project is Node.js v5.5. Build safe_core with the mock Routing feature:  

cargo build --release --features use-mock-routing

  then copy the resulting shared library (safe_core.dll for Windows, libsafe_core.so for Linux or libsafe_core.dylib for OS X) to the app/api/ffi folder of this project.
```

But there is no libsafe_core.so produced.

This worked fairly recently must be due to a recent change in safe_core, but perhaps the oversight is updating these instructions? However, I tried copying libsafe_core.a instead but get an error on running launcher (can't load safe_ffi).

Also, compiling safe_core as instructed above gives a warning at the start about dylib.

**Comment by Viv-Rajkumar** [comment]
Are you on the latest stable rust @theWebalyst you might just need to update rust if you're on 1.10 since the lib type was [updated](https://github.com/maidsafe/safe_core/commit/c778a2ca19ed6f3eb8498fd53c142594b08dd0f1#diff-80398c5faae3c069e4e6aa2ed11b28c0R56). You'll want to see

```
$ rustc --version
rustc 1.11.0 (9b21dcd6a 2016-08-15)
```

> I tried copying libsafe_core.a instead but get an error on running launcher (can't load safe_ffi).

Yeh thats not expected to work. you just need the `.so` if you're on Linux. It should build fine with the latest rust stable.

**Comment by theWebalyst** [comment]
Ah, thanks Viv you're right. [blush]
