### ISSUE TITLE
Failed at the nslog@3.0.0 install script 'node-gyp rebuild' during npm install on Ubuntu 14.04

### ISSUE THREAD

**Issue by jimmco** [maidsafe/safe_launcher#249]
Following https://github.com/maidsafe/safe_launcher/blob/master/README.md and during npm install I get:

Node version: v5.5.0
Npm version: 3.3.12

```
> nslog@3.0.0 install /home/jimmco/data/repo/github.com/maidsafe/safe_launcher/node_modules/nslog
> node-gyp rebuild

make: Entering directory `/home/jimmco/data/repo/github.com/maidsafe/safe_launcher/node_modules/nslog/build'
  CXX(target) Release/obj.target/nslog/src/main.o
In file included from ../src/nslog.h:4:0,
                 from ../src/main.cc:1:
/usr/include/c++/4.8/string:38:28: fatal error: bits/c++config.h: No such file or directory
 #include <bits/c++config.h>
                            ^
compilation terminated.
make: *** [Release/obj.target/nslog/src/main.o] Error 1
make: Leaving directory `/home/jimmco/data/repo/github.com/maidsafe/safe_launcher/node_modules/nslog/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/jimmco/data/lib/node-v5.5.0-linux-x86/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.19.0-32-generic
gyp ERR! command "/home/jimmco/data/lib/node-v5.5.0-linux-x86/bin/node" "/home/jimmco/data/lib/node-v5.5.0-linux-x86/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/jimmco/data/repo/github.com/maidsafe/safe_launcher/node_modules/nslog
gyp ERR! node -v v5.5.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
```

**Comment by frabrunelle** [comment]
@jimmco I just realized that this was mentioned in the last Dev Update. sorry for asking you to open an issue :stuck_out_tongue: 

> The current master branch of safe_launcher is not compatible with the changes made in the safe_core.

> Once the Launcher API v0.6 RFC is raised, Krishna will start working on integrating the FFI changes from the latest safe_core master branch.

https://safenetforum.org/t/maidsafe-dev-update-30th-august-2016/10979

**Comment by jimmco** [comment]
@frabrunelle ok, thanks for clarification

**Comment by frabrunelle** [comment]
Hi @jimmco,

False alarm: turns out it also works fine on Ubuntu. sometimes I have strange issues when I don’t plug my laptop via ethernet so that’s probably the issue I was having (I hadn’t really spend much time debugging). It was working both using the `safe_core` version I compiled yesterday (from the master branch) and using the last tagged version (https://github.com/maidsafe/safe_core/releases/tag/0.19.0)

Can you try building `safe_launcher` using the last tagged version of `safe_core`?

https://github.com/maidsafe/safe_core/releases/tag/0.19.0

I would also recommend deleting your `safe_launcher` repo and cloning it again. or at least just running `rm -rf node_modules` and then running `npm install` again.

also, in case `safe_launcher` gets updated, you could use the source code of the last tagged version: https://github.com/maidsafe/safe_launcher/releases/tag/0.8.1

If it's still not working, it might because of a missing dependency. For example, do you have the `build-essential` package? (`sudo apt-get install build-essential`)

**Comment by krishnaIndia** [comment]
For node-gyp python is also a requirement. This [link](https://github.com/nodejs/node-gyp#installation) should help in getting the node-gyp setup

**Comment by jimmco** [comment]
I've tried all hints but still the same error. I'll try to dig a bit deeper and will see.

**Comment by jimmco** [comment]
After various experiments this helped after all
```cd node_modules/electron-prebuilt && node install.js```
